package de.jave.jave.icon;

import de.jave.jave.application.resources.JaveImageProvider;
import de.jave.preferences.JavePreferences;
import java.awt.Image;
import java.util.Arrays;
import java.util.List;
import javax.swing.Icon;
import net.dizzy.commons.swing.icon.IconScaler;
import net.dizzy.commons.swing.resources.IIconResources;

public class JaveIcons implements IIconResources {
   private static final int ICON_SIZE = JavePreferences.readIconSizePreference();

   public static int getIconSize() {
      return ICON_SIZE;
   }

   private static final Image JAVE_ICON_IMAGE_16x16 = JaveImageProvider.getInstance().getImage("javeicon16.gif");
   private static final Image JAVE_ICON_IMAGE_32x32 = JaveImageProvider.getInstance().getImage("javeicon32.gif");
   private static final Image JAVE_ICON_IMAGE_64x64 = JaveImageProvider.getInstance().getImage("javeicon64.png");
   public static final List<? extends Image> JAVE_ICON_IMAGES = Arrays.asList(JAVE_ICON_IMAGE_16x16, JAVE_ICON_IMAGE_32x32, JAVE_ICON_IMAGE_64x64);
   public static final Icon ANIMATION_ADD_FRAME_ICON = loadIcon("animation/add_frame.gif");
   public static final Icon ANIMATION_CURRENT_FRAME_ITEM_ICON = loadIcon("animation/current_frame.gif");
   public static final Icon ANIMATION_DELETE_FRAME_ICON = loadIcon("animation/delete_frame.gif");
   public static final Icon ANIMATION_DUPLICATE_FRAME_ICON = loadIcon("animation/duplicate_frame.gif");
   public static final Icon ANIMATION_FRAME_ITEM_ICON = loadIcon("animation/frame.gif");
   public static final Icon ANIMATION_MOVE_LEFT_ICON = loadIcon("animation/move_left.gif");
   public static final Icon ANIMATION_MOVE_RIGHT_ICON = loadIcon("animation/move_right.gif");
   public static final Icon ANIMATION_REVERSE_ICON = loadIcon("animation/reverse.gif");
   public static final Icon ANIMATION_MAKING_OF_ICON = loadIcon("animation/makingofasanimation.gif");
   public static final Icon ASCTRIS = loadIcon("asctris.gif");
   public static final Icon BROWSE_ICON = loadIcon("browse.gif");
   public static final Icon CAMEL_ICON = loadIcon("camel.gif");
   public static final Icon CLIPART_ICON = loadIcon("clipart.gif");
   public static final Icon CONNECTED_LINES_VIEW_ICON = loadIcon("pixel_toggle.gif");
   public static final Icon CLIPART_ITEM_ICON = loadIcon("clipart_small.gif");
   public static final Icon MOUSE_ICON = loadIcon("mouse.gif");
   public static final Icon FORMULA_ICON = loadIcon("formula.gif");
   public static final Icon FRACTAL_ICON = loadIcon("fractal.gif");
   public static final Icon GRID_VISIBLE_ICON = loadIcon("grid.gif");
   public static final Icon HELP_ICON = loadIcon("help.gif");
   public static final Icon JAVE_ICON = loadIcon("javeicon16.gif");
   public static final Icon LARGE_EXPORT_WIZARD_ICON = loadIcon("export_wizard.gif");
   public static final Icon PROPERTIES_ICON = loadIcon("properties.gif");
   public static final Icon PURE_ASCII_ICON = loadIcon("pure_toggle.gif");
   public static final Icon RESIZE_ICON = loadIcon("resize.gif");
   public static final Icon TEXTBOX_ICON = loadIcon("textbox.gif");
   public static final Icon TRANSPARENT_ICON = loadIcon("transparent.gif");
   public static final Icon NEW_DOCUMENT_ICON = loadIcon("new.gif");
   public static final Icon OPEN_ICON = loadIcon("open.gif");
   public static final Icon OPEN_RECENT_ICON = loadIcon("open_recent.gif");
   public static final Icon CLOSE_ICON = loadIcon("close.gif");
   public static final Icon SAVE_ALL_EDIT_ICON = loadIcon("saveall_edit.gif");
   public static final Icon SAVE_AS_EDIT_ICON = loadIcon("saveas_edit.gif");
   public static final Icon SAVE_EDIT_ICON = loadIcon("save_edit.gif");
   public static final Icon CAMELIZER_DIALOGICON = loadIcon("camelizer_dialogicon.gif");
   public static final Icon EXPORT_ANIMATION_ICON = loadIcon("export_animation.gif");
   public static final Icon EXPORT_CLIPART_ICON = loadIcon("export_clipart.gif");
   public static final Icon EXPORT_FIGLET_ICON = loadIcon("export_figlet.gif");
   public static final Icon EXPORT_ICON = loadIcon("export.gif");
   public static final Icon IMPORT_ICON = loadIcon("import.gif");
   public static final Icon FLIP_DYNAMIC_ICON = loadIcon("menu/flip_dynamic.gif");
   public static final Icon FLIP_STATIC_ICON = loadIcon("menu/flip_static.gif");
   public static final Icon MIRROR_DYNAMIC_ICON = loadIcon("menu/mirror_dynamic.gif");
   public static final Icon MIRROR_STATIC_ICON = loadIcon("menu/mirror_static.gif");
   public static final Icon NAVIGATE_MOVE_DOWN = loadIcon("navigate/move_down.gif");
   public static final Icon NAVIGATE_MOVE_LEFT = loadIcon("navigate/move_left.gif");
   public static final Icon NAVIGATE_MOVE_RIGHT = loadIcon("navigate/move_right.gif");
   public static final Icon NAVIGATE_MOVE_UP = loadIcon("navigate/move_up.gif");
   public static final Icon NAVIGATE_NAVIGATE_IN = loadIcon("navigate/navigate_in.gif");
   public static final Icon NAVIGATE_NAVIGATE_OUT = loadIcon("navigate/navigate_out.gif");
   public static final Icon NAVIGATE_RESET = loadIcon("navigate/reset.gif");
   public static final Icon NAVIGATE_ROTATE_LEFT = loadIcon("navigate/rotate_left.gif");
   public static final Icon NAVIGATE_ROTATE_RIGHT = loadIcon("navigate/rotate_right.gif");
   public static final Icon ROTATE_180_ICON = loadIcon("menu/rotate_180.gif");
   public static final Icon ROTATE_90_LEFT_ICON = loadIcon("menu/rotate_90left.gif");
   public static final Icon ROTATE_90_RIGHT_ICON = loadIcon("menu/rotate_90right.gif");
   public static final Icon ROTATE_DYNAMIC_ICON = loadIcon("menu/rotate_dynamic.gif");
   public static final Icon ROTATE_NONE_ICON = loadIcon("menu/rotate_none.gif");
   public static final Icon ROTATE_STATIC_ICON = loadIcon("menu/rotate_static.gif");
   public static final Icon RULER_ICON = loadIcon("ruler.gif");
   public static final Icon TOOL_ARC_GENERIC_ICON = loadIcon("tool/arc_generic.gif");
   public static final Icon TOOL_BEZIER_GENERIC_ICON = loadIcon("tool/bezier_generic.gif");
   public static final Icon TOOL_BRUSH_ICON = loadIcon("tool/brush.gif");
   public static final Icon TOOL_CLONE_BRUSH_ICON = loadIcon("tool/clone_brush.gif");
   public static final Icon TOOL_ELLIPSE_GENERIC_ICON = loadIcon("tool/ellipse_generic.gif");
   public static final Icon TOOL_ERASER_ICON = loadIcon("tool/eraser.gif");
   public static final Icon TOOL_FIGLET_ICON = loadIcon("tool/figlet.gif");
   public static final Icon TOOL_FREEHAND_GENERIC_ICON = loadIcon("tool/freehand_generic.gif");
   public static final Icon TOOL_FREEHAND_SELECTION_ICON = loadIcon("tool/freehand_selection.gif");
   public static final Icon TOOL_LINE_GENERIC_ICON = loadIcon("tool/line_generic.gif");
   public static final Icon TOOL_PAN_ICON = loadIcon("tool/pan.gif");
   public static final Icon TOOL_RECTANGLE_GENERIC_ICON = loadIcon("tool/rectangle_generic.gif");
   public static final Icon TOOL_SELECTION_ICON = loadIcon("tool/selection.gif");
   public static final Icon TOOL_WATERMARK_ICON = loadIcon("tool/watermark.gif");
   public static final Icon TOOL_AUXILIARY_LINES_ICON = loadIcon("tool/auxlines.gif");
   public static final Icon TOOL_ELLISPE_ALGORITHMIC_ICON = loadIcon("tool/ellipse.gif");
   public static final Icon TOOL_FILL_ICON = loadIcon("tool/fill.gif");
   public static final Icon TOOL_FREEHAND_ALGORITHMIC_ICON = loadIcon("tool/freehand.gif");
   public static final Icon TOOL_LINE_ALGORITHMIC_ICON = loadIcon("tool/line.gif");
   public static final Icon TOOL_RECTANGLE_ALGORITHMIC_ICON = loadIcon("tool/rectangle.gif");
   public static final Icon TOOL_TEXT_ICON = loadIcon("tool/text.gif");
   public static final Icon TOOLTYPE_ALGORITHMIC_ICON = loadIcon("tool/tool_algorithmic.gif");
   public static final Icon TOOLTYPE_GENERIC_ICON = loadIcon("tool/tool_generic.gif");
   public static final Icon ZOOM_MINUS_ICON = loadIcon("zoomminus.gif");
   public static final Icon ZOOM_PLUS_ICON = loadIcon("zoomplus.gif");
   public static final Icon GRADIENT_RADIAL_ICON = loadIcon("gradient/radial.gif");
   public static final Icon GRADIENT_SUNBURST_ICON = loadIcon("gradient/sunburst.gif");
   public static final Icon GRADIENT_LINEAR_ICON = loadIcon("gradient/linear.gif");
   public static final Icon COLOR_SCHEME_BLACK_ON_GRAY = loadIcon("color/color_black_on_gray.gif");
   public static final Icon COLOR_SCHEME_WHITE_ON_BLACK = loadIcon("color/color_white_on_black.gif");
   public static final Icon COLOR_SCHEME_BLACK_ON_WHITE = loadIcon("color/color_black_on_white.gif");
   public static final Icon CURSORMOVE_TRACK_FOLLOWING = loadIcon("textcursor/direction_trackfollowing.gif");
   public static final Icon CURSORMOVE_NORMAL = loadIcon("textcursor/direction_normal.gif");
   public static final Icon CURSORMOVE_NONE = loadIcon("textcursor/direction_none.gif");
   public static final Icon CURSORMOVE_DIRECTED = loadIcon("textcursor/direction_directed.gif");
   public static final Icon PENCIL1 = loadIcon("pencil/roundsize1.gif");
   public static final Icon PENCIL1_DISABLED = loadIcon("pencil/roundsize1_.gif");
   public static final Icon PENCIL4 = loadIcon("pencil/roundsize4.gif");
   public static final Icon PENCIL4_DISABLED = loadIcon("pencil/roundsize4_.gif");
   public static final Icon PENCIL5 = loadIcon("pencil/roundsize5.gif");
   public static final Icon PENCIL5_DISABLED = loadIcon("pencil/roundsize5_.gif");
   public static final Icon PENCIL6 = loadIcon("pencil/roundsize6.gif");
   public static final Icon PENCIL6_DISABLED = loadIcon("pencil/roundsize6_.gif");
   public static final Icon PENCIL7 = loadIcon("pencil/roundsize7.gif");
   public static final Icon PENCIL7_DISABLED = loadIcon("pencil/roundsize7_.gif");

   private static Icon loadIcon(String name) {
      return IconScaler.scaleToPreferredSize(JaveImageProvider.getInstance().getImageIcon(name), ICON_SIZE);
   }
}
